# Change these first
owner: krakendeploy-com # Your GitHub organization or username, where this repository lives
repo: kraken-status # The name of this repository

sites:
  - name: Kraken Site
    url: https://www.krakendeploy.com
  - name: Kraken API
    url: https://api.krakendeploy.com/health
  - name: Kraken Agent API
    url: https://agent-api.krakendeploy.com/health
  - name: Kraken Auth
    url: https://auth.krakendeploy.com/health
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.krakendeploy.com
  #baseUrl: /kraken-status
  logoUrl: https://raw.githubusercontent.com/krakendeploy-com/kraken-status/HEAD/assets/logo.png
  name: Kraken Deploy Status
  introTitle: "**Kraken Deploy** System Status"
  introMessage: Real-time monitoring and status updates for all Kraken Deploy services. This page provides live uptime data, response times, and incident reports for our platform.
  navbar:
    - title: Status
      href: /
    - title: Main Site
      href: https://www.krakendeploy.com
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  favicon: https://raw.githubusercontent.com/krakendeploy-com/kraken-status/HEAD/assets/icon-192.png
  faviconSvg: https://raw.githubusercontent.com/krakendeploy-com/kraken-status/HEAD/assets/logo.png
  theme: dark
  customHeadHtml: |
    <style>
      body { background-color: #111418 !important; }
    </style>
  css:
    - https://raw.githubusercontent.com/krakendeploy-com/kraken-status/HEAD/assets/custom.css

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
